/* ============================================================
   Academic Atlas — seed data (v1, hand-curated mockup data)
   ============================================================
   This file is the ONLY place data lives. The UI (app.js) reads
   ATLAS_DATA and nothing else, so v2 can replace this file with
   scraped / submitted data without touching presentation code.

   SCHEMA — every item shares a common core:
     id           unique slug, prefixed by cluster
     cluster      "conference" | "special-issue" | "course"
     acronym      short display name ("ICIS 2026")
     title        full official name
     disciplines  array of: "IS" | "ENT" | "FIN"
     ranking      { label: display string, band: "top" | "high" | "na" }
                  band powers the ranking filter; label is shown as-is
     deadline     ISO date of the NEXT actionable deadline
     deadlineLabel what the deadline is for ("Full paper submission")
     location     { city, country } — null for special issues
     region       "Europe" | "North America" | "Asia-Pacific" | null
     format       "onsite" | "hybrid" | "online" | null (null for SIs)
     fee          display string; feeType: "free" | "paid" (filterable)
     officialUrl  the venue/journal homepage
     submitUrl    DIRECT link to the submission/registration system.
                  Never omit this — dead-ending at a homepage is the
                  #1 failure of existing tools.
     description  1–2 sentence plain-language summary
     verified     ISO date this entry was last human-checked

   Cluster-specific sub-objects (exactly one per item):
     conference:   { dates, acceptanceRate, theme, doctoralConsortium }
     specialIssue: { journal, journalRanking, topics[], guidelinesUrl }
     course:       { period, university, ects, requirements, assessment }
   ============================================================ */

const ATLAS_DATA = {
  meta: {
    version: "v1-seed",
    lastUpdated: "2026-07-14",
    disciplines: {
      IS: "Information Systems",
      ENT: "Entrepreneurship & Management",
      FIN: "Finance & Economics",
    },
  },

  items: [
    /* ---------------- Conferences ---------------- */
    {
      id: "conf-hicss-60",
      cluster: "conference",
      acronym: "HICSS-60",
      title: "Hawaii International Conference on System Sciences",
      disciplines: ["IS"],
      ranking: { label: "CORE A", band: "high" },
      deadline: "2026-07-20",
      deadlineLabel: "Full paper submission",
      location: { city: "Maui", country: "USA" },
      region: "North America",
      format: "onsite",
      fee: "$1,150 regular registration",
      feeType: "paid",
      officialUrl: "https://hicss.hawaii.edu",
      submitUrl: "https://new.precisionconference.com/hicss",
      description:
        "Broad systems-sciences conference with strong IS mini-tracks; a common first outlet for PhD work in decision analytics and digital innovation.",
      verified: "2026-07-12",
      conference: {
        dates: "Jan 5–8, 2027",
        acceptanceRate: "~48%",
        theme: "Decision analytics, digital innovation and emerging technology tracks",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-icis-2026",
      cluster: "conference",
      acronym: "ICIS 2026",
      title: "International Conference on Information Systems",
      disciplines: ["IS"],
      ranking: { label: "CORE A*", band: "top" },
      deadline: "2026-09-01",
      deadlineLabel: "Short papers & posters",
      location: { city: "Munich", country: "Germany" },
      region: "Europe",
      format: "onsite",
      fee: "$1,095 member early bird",
      feeType: "paid",
      officialUrl: "https://icis2026.aisnet.org",
      submitUrl: "https://new.precisionconference.com/icis",
      description:
        "The flagship AIS conference and the most competitive general IS venue; the doctoral consortium is by nomination and highly regarded.",
      verified: "2026-07-10",
      conference: {
        dates: "Dec 13–16, 2026",
        acceptanceRate: "~27%",
        theme: "Digital frontiers and responsible information systems",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-ecis-2027",
      cluster: "conference",
      acronym: "ECIS 2027",
      title: "European Conference on Information Systems",
      disciplines: ["IS"],
      ranking: { label: "CORE A", band: "high" },
      deadline: "2026-11-17",
      deadlineLabel: "Research paper submission",
      location: { city: "Valencia", country: "Spain" },
      region: "Europe",
      format: "onsite",
      fee: "€680 early bird",
      feeType: "paid",
      officialUrl: "https://ecis2027.eu",
      submitUrl: "https://new.precisionconference.com/ecis",
      description:
        "Europe's leading IS conference; research-in-progress track and consortium make it especially accessible for second-year PhD students.",
      verified: "2026-07-14",
      conference: {
        dates: "Jun 14–18, 2027",
        acceptanceRate: "~32%",
        theme: "Human-centred digitalisation",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-ispim-2026",
      cluster: "conference",
      acronym: "ISPIM Summit 2026",
      title: "ISPIM Innovation Summit",
      disciplines: ["ENT"],
      ranking: { label: "Leading innovation conference", band: "high" },
      deadline: "2026-08-30",
      deadlineLabel: "Extended abstract (outline) submission",
      location: { city: "Melbourne", country: "Australia" },
      region: "Asia-Pacific",
      format: "hybrid",
      fee: "€980 standard",
      feeType: "paid",
      officialUrl: "https://www.ispim-innovation.com",
      submitUrl: "https://www.conftool.net/ispim-summit-2026",
      description:
        "Practice-oriented innovation management community; outline-based submission keeps the entry barrier low for early-stage work.",
      verified: "2026-07-09",
      conference: {
        dates: "Dec 6–9, 2026",
        acceptanceRate: "~60%",
        theme: "Innovation in and for turbulent times",
        doctoralConsortium: false,
      },
    },
    {
      id: "conf-aom-2027",
      cluster: "conference",
      acronym: "AOM 2027",
      title: "Academy of Management Annual Meeting",
      disciplines: ["ENT"],
      ranking: { label: "Flagship · AOM", band: "top" },
      deadline: "2027-01-12",
      deadlineLabel: "Scholarly papers & symposia",
      location: { city: "Seattle", country: "USA" },
      region: "North America",
      format: "onsite",
      fee: "$420 + AOM membership",
      feeType: "paid",
      officialUrl: "https://aom.org/events/annual-meeting",
      submitUrl: "https://aom.org/events/annual-meeting/submitting",
      description:
        "The largest management conference worldwide; the ENT division's doctoral and junior-faculty consortia are a rite of passage in the field.",
      verified: "2026-07-13",
      conference: {
        dates: "Aug 6–10, 2027",
        acceptanceRate: "~50%",
        theme: "Theme to be announced (division CFPs open October 2026)",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-euram-2027",
      cluster: "conference",
      acronym: "EURAM 2027",
      title: "European Academy of Management Conference",
      disciplines: ["ENT"],
      ranking: { label: "Major European venue", band: "high" },
      deadline: "2027-01-19",
      deadlineLabel: "Full paper submission",
      location: { city: "Rotterdam", country: "Netherlands" },
      region: "Europe",
      format: "onsite",
      fee: "€590 early bird",
      feeType: "paid",
      officialUrl: "https://conferences.euram.academy",
      submitUrl: "https://conferences.euram.academy/2027/submission",
      description:
        "Track-based European management conference with a dedicated doctoral colloquium in the two days before the main programme.",
      verified: "2026-07-11",
      conference: {
        dates: "Jun 22–25, 2027",
        acceptanceRate: "~55%",
        theme: "Managing with purpose in a fragmented world",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-afa-2027",
      cluster: "conference",
      acronym: "AFA 2027",
      title: "American Finance Association Annual Meeting",
      disciplines: ["FIN"],
      ranking: { label: "Flagship · AFA", band: "top" },
      deadline: "2026-07-29",
      deadlineLabel: "Paper submission",
      location: { city: "Chicago", country: "USA" },
      region: "North America",
      format: "onsite",
      fee: "Free submission · AFA membership $90",
      feeType: "paid",
      officialUrl: "https://afajof.org/annual-meeting",
      submitUrl: "https://afajof.org/annual-meeting/submissions",
      description:
        "The premier finance meeting (held within ASSA); the PhD poster session is the standard way for doctoral students to get on the programme.",
      verified: "2026-07-13",
      conference: {
        dates: "Jan 3–5, 2027",
        acceptanceRate: "~10%",
        theme: "General programme across all fields of finance",
        doctoralConsortium: true,
      },
    },
    {
      id: "conf-wfa-2027",
      cluster: "conference",
      acronym: "WFA 2027",
      title: "Western Finance Association Annual Meeting",
      disciplines: ["FIN"],
      ranking: { label: "Top field conference", band: "top" },
      deadline: "2026-11-10",
      deadlineLabel: "Paper submission",
      location: { city: "Whistler", country: "Canada" },
      region: "North America",
      format: "onsite",
      fee: "$85 submission fee",
      feeType: "paid",
      officialUrl: "https://westernfinance.org",
      submitUrl: "https://westernfinance.org/submit",
      description:
        "Highly selective single-track finance meeting; a WFA acceptance is a strong job-market signal for finance PhDs.",
      verified: "2026-07-08",
      conference: {
        dates: "Jun 20–23, 2027",
        acceptanceRate: "~8%",
        theme: "General programme, asset pricing and corporate finance heavy",
        doctoralConsortium: false,
      },
    },

    /* ---------------- Special issues ---------------- */
    {
      id: "si-jais-responsible-dsr",
      cluster: "special-issue",
      acronym: "JAIS SI",
      title: "Responsible Design Science Research",
      disciplines: ["IS"],
      ranking: { label: "AIS Basket · ABS 4", band: "top" },
      deadline: "2026-08-10",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "No submission fee",
      feeType: "free",
      officialUrl: "https://aisel.aisnet.org/jais",
      submitUrl: "https://mc.manuscriptcentral.com/jais",
      description:
        "Special issue on embedding ethics, sustainability and societal impact into design science methodology and artefacts.",
      verified: "2026-07-12",
      specialIssue: {
        journal: "Journal of the Association for Information Systems",
        journalRanking: "AIS Senior Scholars' Basket · ABS 4",
        topics: [
          "Ethics-by-design in DSR projects",
          "Evaluation of societal impact of artefacts",
          "Responsible AI artefact design",
        ],
        guidelinesUrl: "https://aisel.aisnet.org/jais/authorinfo.html",
      },
    },
    {
      id: "si-misq-genai",
      cluster: "special-issue",
      acronym: "MISQ SI",
      title: "Generative AI and the Future of Organizing",
      disciplines: ["IS"],
      ranking: { label: "AIS Basket · FT50 · ABS 4*", band: "top" },
      deadline: "2026-09-30",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "No submission fee",
      feeType: "free",
      officialUrl: "https://misq.umn.edu",
      submitUrl: "https://mc.manuscriptcentral.com/misq",
      description:
        "MISQ call on how generative AI reshapes coordination, expertise and control in organisations; welcomes qualitative, quantitative and design work.",
      verified: "2026-07-14",
      specialIssue: {
        journal: "MIS Quarterly",
        journalRanking: "AIS Senior Scholars' Basket · FT50 · ABS 4*",
        topics: [
          "Human–AI collaboration and delegation",
          "GenAI and the transformation of knowledge work",
          "Governance of generative systems in organisations",
        ],
        guidelinesUrl: "https://misq.umn.edu/instructions-for-authors",
      },
    },
    {
      id: "si-jbf-climate",
      cluster: "special-issue",
      acronym: "JBF SI",
      title: "Climate Risk, Transition Finance and Bank Stability",
      disciplines: ["FIN"],
      ranking: { label: "ABS 3 · ABDC A*", band: "high" },
      deadline: "2026-10-01",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "$250 submission fee",
      feeType: "paid",
      officialUrl: "https://www.sciencedirect.com/journal/journal-of-banking-and-finance",
      submitUrl: "https://www.editorialmanager.com/jbf",
      description:
        "Empirical and theoretical work on how climate transition risk propagates through bank balance sheets, lending and regulation.",
      verified: "2026-07-10",
      specialIssue: {
        journal: "Journal of Banking & Finance",
        journalRanking: "ABS 3 · ABDC A*",
        topics: [
          "Climate stress testing and capital requirements",
          "Green lending and credit allocation",
          "Transition risk pricing in loan and bond markets",
        ],
        guidelinesUrl:
          "https://www.sciencedirect.com/journal/journal-of-banking-and-finance/publish/guide-for-authors",
      },
    },
    {
      id: "si-jbv-genai-ent",
      cluster: "special-issue",
      acronym: "JBV SI",
      title: "Entrepreneurship in the Age of Generative AI",
      disciplines: ["ENT"],
      ranking: { label: "FT50 · ABS 4*", band: "top" },
      deadline: "2026-10-15",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "No submission fee",
      feeType: "free",
      officialUrl: "https://www.sciencedirect.com/journal/journal-of-business-venturing",
      submitUrl: "https://www.editorialmanager.com/jbv",
      description:
        "How generative AI changes opportunity recognition, venture creation and the economics of being a founder.",
      verified: "2026-07-11",
      specialIssue: {
        journal: "Journal of Business Venturing",
        journalRanking: "FT50 · ABS 4*",
        topics: [
          "AI-augmented opportunity evaluation",
          "Solo founders and AI-leveraged scaling",
          "Entrepreneurial ecosystems for AI ventures",
        ],
        guidelinesUrl:
          "https://www.sciencedirect.com/journal/journal-of-business-venturing/publish/guide-for-authors",
      },
    },
    {
      id: "si-etp-ecosystems",
      cluster: "special-issue",
      acronym: "ETP SI",
      title: "Entrepreneurial Ecosystems and Regional Renewal",
      disciplines: ["ENT"],
      ranking: { label: "FT50 · ABS 4", band: "top" },
      deadline: "2026-11-30",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "No submission fee",
      feeType: "free",
      officialUrl: "https://journals.sagepub.com/home/etp",
      submitUrl: "https://mc.manuscriptcentral.com/etp",
      description:
        "Multi-level research on how entrepreneurial ecosystems form, decline and regenerate regions — comparative and longitudinal designs encouraged.",
      verified: "2026-07-09",
      specialIssue: {
        journal: "Entrepreneurship Theory and Practice",
        journalRanking: "FT50 · ABS 4",
        topics: [
          "Ecosystem emergence and path dependence",
          "Policy interventions and regional renewal",
          "Ecosystem measurement and methods",
        ],
        guidelinesUrl: "https://journals.sagepub.com/author-instructions/ETP",
      },
    },
    {
      id: "si-isr-resilience",
      cluster: "special-issue",
      acronym: "ISR SI",
      title: "Digital Resilience in Turbulent Environments",
      disciplines: ["IS"],
      ranking: { label: "AIS Basket · FT50 · ABS 4*", band: "top" },
      deadline: "2026-12-01",
      deadlineLabel: "Full paper submission",
      location: null,
      region: null,
      format: null,
      fee: "No submission fee",
      feeType: "free",
      officialUrl: "https://pubsonline.informs.org/journal/isre",
      submitUrl: "https://mc.manuscriptcentral.com/isr",
      description:
        "How digital infrastructures and organisations absorb, adapt to and recover from shocks — from cyber incidents to supply-chain disruption.",
      verified: "2026-07-13",
      specialIssue: {
        journal: "Information Systems Research",
        journalRanking: "AIS Senior Scholars' Basket · FT50 · ABS 4*",
        topics: [
          "Resilience of digital infrastructures",
          "Crisis response and digital improvisation",
          "Antifragile IS architectures",
        ],
        guidelinesUrl:
          "https://pubsonline.informs.org/page/isre/submission-guidelines",
      },
    },

    /* ---------------- Summer schools / PhD courses ---------------- */
    {
      id: "course-utrecht-qual-2026",
      cluster: "course",
      acronym: "Utrecht Summer School",
      title: "Advanced Qualitative Research Methods",
      disciplines: ["IS", "ENT"],
      ranking: { label: "3 ECTS", band: "na" },
      deadline: "2026-07-22",
      deadlineLabel: "Application deadline",
      location: { city: "Utrecht", country: "Netherlands" },
      region: "Europe",
      format: "onsite",
      fee: "€750 course fee",
      feeType: "paid",
      officialUrl: "https://utrechtsummerschool.nl",
      submitUrl: "https://utrechtsummerschool.nl/apply",
      description:
        "One-week intensive on interview, case and process methods; built around participants' own dissertation projects.",
      verified: "2026-07-11",
      course: {
        period: "Aug 17–21, 2026",
        university: "Utrecht University",
        ects: 3,
        requirements: "Enrolled PhD student; short motivation letter and project abstract",
        assessment: "Graded research-design paper (pass/fail)",
      },
    },
    {
      id: "course-eden-case-2026",
      cluster: "course",
      acronym: "EIASM EDEN",
      title: "Doctoral Seminar on Case Study Research",
      disciplines: ["IS", "ENT"],
      ranking: { label: "4 ECTS", band: "na" },
      deadline: "2026-08-31",
      deadlineLabel: "Application deadline",
      location: { city: "Brussels", country: "Belgium" },
      region: "Europe",
      format: "onsite",
      fee: "€1,300 · €980 for EIASM member institutions",
      feeType: "paid",
      officialUrl: "https://www.eiasm.org/frontoffice/eden_announcements.asp",
      submitUrl: "https://www.eiasm.org/frontoffice/event_registration.asp",
      description:
        "Classic EDEN seminar on designing and publishing case-study research, taught by senior faculty; small cohort, heavy feedback.",
      verified: "2026-07-12",
      course: {
        period: "Oct 12–16, 2026",
        university: "EIASM (Brussels)",
        ects: 4,
        requirements: "PhD students in management-related fields; extended abstract of thesis project",
        assessment: "Active participation and presentation of own case design",
      },
    },
    {
      id: "course-cbs-panel-2026",
      cluster: "course",
      acronym: "CBS PhD Course",
      title: "Panel Data Econometrics for Finance",
      disciplines: ["FIN"],
      ranking: { label: "5 ECTS", band: "na" },
      deadline: "2026-09-15",
      deadlineLabel: "Application deadline",
      location: { city: "Copenhagen", country: "Denmark" },
      region: "Europe",
      format: "hybrid",
      fee: "Free for partner universities · DKK 5,000 otherwise",
      feeType: "paid",
      officialUrl: "https://www.cbs.dk/en/research/phd-programmes/phd-courses",
      submitUrl: "https://phd.cbs.dk/course-registration",
      description:
        "Applied panel-data methods (FE/RE, diff-in-diff, dynamic panels) with finance applications; bring your own dataset for the assignment.",
      verified: "2026-07-10",
      course: {
        period: "Nov 2–6, 2026",
        university: "Copenhagen Business School",
        ects: 5,
        requirements: "First-year econometrics; own research dataset recommended",
        assessment: "Take-home empirical assignment, graded pass/fail",
      },
    },
    {
      id: "course-jibs-ent-2027",
      cluster: "course",
      acronym: "JIBS PhD Course",
      title: "Frontiers of Entrepreneurship Research",
      disciplines: ["ENT"],
      ranking: { label: "7.5 ECTS", band: "na" },
      deadline: "2026-10-01",
      deadlineLabel: "Application deadline",
      location: { city: "Jönköping", country: "Sweden" },
      region: "Europe",
      format: "onsite",
      fee: "Free · travel & accommodation self-funded",
      feeType: "free",
      officialUrl: "https://ju.se/en/research/phd-studies.html",
      submitUrl: "https://ju.se/en/research/phd-studies/apply",
      description:
        "Reading-intensive doctoral course at one of Europe's strongest entrepreneurship groups; maps the field's current debates.",
      verified: "2026-07-13",
      course: {
        period: "Jan 18–22, 2027",
        university: "Jönköping International Business School",
        ects: 7.5,
        requirements: "Doctoral students in entrepreneurship or management; pre-course reading package",
        assessment: "Individual review essay and seminar discussion lead",
      },
    },
    {
      id: "course-gserm-ml-2027",
      cluster: "course",
      acronym: "GSERM Winter School",
      title: "Machine Learning for Empirical Research",
      disciplines: ["IS", "FIN"],
      ranking: { label: "4 ECTS", band: "na" },
      deadline: "2026-10-31",
      deadlineLabel: "Application deadline",
      location: { city: "St. Gallen", country: "Switzerland" },
      region: "Europe",
      format: "onsite",
      fee: "CHF 1,100 PhD rate",
      feeType: "paid",
      officialUrl: "https://gserm.org",
      submitUrl: "https://gserm.org/registration",
      description:
        "GSERM's methods week at the University of St. Gallen; hands-on ML for social-science research questions in R/Python.",
      verified: "2026-07-14",
      course: {
        period: "Jan 11–15, 2027",
        university: "University of St. Gallen",
        ects: 4,
        requirements: "Basic statistics; working knowledge of R or Python",
        assessment: "Written exam on the final day",
      },
    },
  ],
};
